"""add stage position

Revision ID: 01121219b552
Revises: 3f54cb4d0b52
Create Date: 2026-07-06 18:35:42.469046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01121219b552'
down_revision: Union[str, Sequence[str], None] = '3f54cb4d0b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'position')
    # ### end Alembic commands ###
