"""drop position column

Revision ID: f288b2ea3862
Revises: 01121219b552
Create Date: 2026-07-07 13:00:04.822087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f288b2ea3862'
down_revision: Union[str, Sequence[str], None] = '01121219b552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('position', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
